name: auto-build

on: [push]

jobs:
  build-windows:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build
      run: |
        npm ci
        npm run win64
      env:
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    - name: pack
      uses: juankaram/archive-action@v1.0.0
      with:
        args : "tar -zvcf ./dist/bilimini-win64-latest.zip ./dist/win-unpack/"
  
  build-mac:

    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build
      run: |
        npm ci
        npm run mac
      env:
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

